Add support for BIQU Printers
SoftFever/OrcaSlicer pull request #1024
Opened 2023-05-09 22:27 UTC by Musicdad12

Adds printers BIQU B1, BX, and Hurakan

2023-05-09 23:26 UTC, SoftFever commented on resources/profiles/BIQU/BIQU_BX_buildplate_texture.png
Can we change the image size to 1024x1024?
Some machines will have issues rendering irregular large textures.

2023-05-09 23:26 UTC, SoftFever commented on resources/profiles/BIQU/BIQU_Hurakan_buildplate_texture.png
Can we change the image size to 512x512 or 1024x1024?
Some machines will have issues rendering irregular large textures.

2023-05-09 23:26 UTC, SoftFever commented on resources/profiles/BIQU/BIQU_B1_buildplate_texture.png
Can we change the image size to 512x512 or 1024x1024?
Some machines will have issues rendering irregular large textures.

2023-05-09 23:31 UTC, SoftFever commented on resources/profiles/BIQU/BIQU_B1_hotend.stl
There's no need to copy this STL and add it to the folder, as OrcaSlicer will automatically use the default hotend model if the machine model doesn't specify a hotend model or if it can't find the specified model.

2023-05-09 23:43 UTC, SoftFever requested changes
@Musicdad12 
Thank you for creating the profiles. 
I noticed a few issues in the PR, so please take a look when you have a chance. Once the modifications have been made, you can test whether the changes are working by updating the version number in BIQU.json. This will force the copying of new profiles to the system folder.

2023-05-09 23:43 UTC, SoftFever commented on resources/profiles/BIQU/BIQU_BX_hotend.stl
It might not be a good idea to use a large hotend model, as it could block the view in the gcode preview window.

2023-05-09 23:43 UTC, SoftFever commented on resources/profiles/BIQU/BIQU_Hurakan_hotend.stl
It might not be a good idea to use a large hotend model, as it could block the view in the gcode preview window.

2023-05-09 23:43 UTC, SoftFever commented on resources/profiles/BIQU.json
> +            "name": "BIQU Generic ABS",
Inconsistent filament name, the name defined inside `BIQU Generic ABS.json` file is `Generic ABS @BIQU`
I don't think it will work

2023-05-09 23:43 UTC, SoftFever commented on resources/profiles/BIQU.json
> +            "name": "BIQU Generic ABS",
Same for all other filament name

2023-05-09 23:43 UTC, SoftFever commented
@Musicdad12
Thank you for creating the profiles.
I noticed a few issues in the PR, so please take a look when you have a chance. Once the modifications have been made, you can test whether the changes are working by updating the version number in BIQU.json. This will force the copying of new profiles to the system folder.

2023-05-10 12:32 UTC, Musicdad12 commented
All requested changes were made.

2023-05-10 14:31 UTC, SoftFever approved these changes
LGTM

2023-05-10 14:32 UTC, merged

2023-05-13 00:53 UTC, Musicdad12 commented
Did you get the cover photos? or do I need to upload them?

2023-05-13 01:25 UTC, SoftFever commented
Hi @Musicdad12 
Thanks @fr3ak2402, he added cover photos for these printers.

2023-05-24 19:55 UTC, Radbmx commented
the biqu profiles will not load after selecting them in the add/remove.  All other printers were working fine
![image](https://github.com/SoftFever/OrcaSlicer/assets/134550573/81399984-a99a-4ae6-a76d-410482c22f86)
![image](https://github.com/SoftFever/OrcaSlicer/assets/134550573/d0d37ddd-e3d1-4407-9265-886faaee8712)

2023-05-24 21:23 UTC, fr3ak2402 commented
@Radbmx 
I have already noticed the problem and have already fixed it, which will be installed in the next few days.