add more printer profiles
SoftFever/OrcaSlicer pull request #1038
Opened 2023-05-11 15:28 UTC by fr3ak2402

Changes:
Removal of the Artillery Sidewinder X1 Printing Plates Texture, as it is redundant and has been replaced with a new version.

New printers:

Artillery Sidewinder X1:
Printer image (180x180)
Custom Printing Plate Texture (512x512)(SVG) - the manufacturer plate imitated
0.4 Nozzle Profile
0.15 Process Profile (Optimal)
0.20 Process Profile (Standard)
0.25 Process Profile (Draft)

Elegoo Neptune:
Printer image (180x180)
Custom Printing Plate Texture (PNG) - the manufacturer plate imitated
0.4 Nozzle Profile
0.08 Process Profile (Extra Fine)
0.12 Process Profile (Fine)
0.16 Process Profile (Optimal)
0.20 Process Profile (Standard)
0.24 Process Profile (Draft)
0.28 Process Profile (Extra Draft)

2023-05-11 15:49 UTC, SoftFever requested changes

2023-05-11 15:51 UTC, fr3ak2402 commented on resources/profiles/Elegoo/machine/Elegoo Neptune 2S 0.4 nozzle.json
> +	"machine_start_gcode": "M413 S0 ; disable Power Loss Recovery\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S120 ; set temporary nozzle temp to prevent oozing during homing and
Yes wait have made a mistake, when replacing and adding the printers

2023-05-11 15:56 UTC, fr3ak2402 commented on resources/profiles/Elegoo/machine/Elegoo Neptune 2S 0.4 nozzle.json
> +	"machine_start_gcode": "M413 S0 ; disable Power Loss Recovery\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S120 ; set temporary nozzle temp to prevent oozing during homing and
@SoftFever 
So I have adjusted it, I must have made a mistake earlier when copying the files

2023-05-11 16:04 UTC, fr3ak2402 commented on resources/profiles/Elegoo/machine/Elegoo Neptune 2S 0.4 nozzle.json
> +	"machine_start_gcode": "M413 S0 ; disable Power Loss Recovery\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S120 ; set temporary nozzle temp to prevent oozing during homing and
@SoftFever
now it should fit again everything with the start code parameters

2023-05-12 10:43 UTC, SoftFever approved these changes

2023-05-12 10:45 UTC, SoftFever commented
Looks good.
You're the man!

2023-05-12 10:45 UTC, merged