Sandwich wall mode can be optimized when perimeters are shared with multiple islands
SoftFever/OrcaSlicer pull request #1352
Opened 2023-06-15 10:54 UTC by igiannakas

PR containing the change in approach to handling sandwich mode when using Arachne engine.

In a nutshell instead of treating the perimeters as inside to outside and re-ordering the last extrusion it flips it to treat them as outside to inside and swaps the order of printing the third wall with the outer perimeter so the order is internal, external, internal.

This means that when less than 3 extrusions exist the wall is treated as outside to inside, leading to a better surface finish as there is no variation due to printing an external perimeter with and without an adjoining internal perimeter

This is a revised version of the PR 751 with more extensive logic on the wall ordering to ensure that all cases where an external perimeter is used are re-ordered correctly, even if there are multiple external perimeters within the same island.

2023-06-25 04:29 UTC, SoftFever requested changes

2023-06-25 04:29 UTC, SoftFever commented on src/libslic3r/PerimeterGenerator.cpp
> +                        swapped_extrusions[0] = ordered_extrusions[outer]; // get the extrusions that need re-ordering into temporary array.
It's better to use swap function here instead of the a temporary vector.

2023-06-25 04:49 UTC, SoftFever commented
The overall logic seems fine to me. It could be optimized or simplified. I have some suggestions in my comment. Let me know if you want me to commit changes into this branch directly. If not, I'm happy to let you do it yourself.

2023-06-25 07:06 UTC, igiannakas commented
> The overall logic seems fine to me. It could be optimized or simplified. I have some suggestions in my comment. Let me know if you want me to commit changes into this branch directly. If not, I'm happy to let you do it yourself.

I couldn’t get the swap function for some reason to work consistently - I’m sure it’s a debug issue but couldn’t find a solution to it. I’d appreciate your help on that please.

2023-06-28 17:06 UTC, SoftFever commented
@igiannakas 
I can't make the swap function work either.
So I have to use a temporary variable :)
Please take a look at my changes and let me know if you have any issues with the changes

2023-06-28 17:41 UTC, igiannakas commented
> @igiannakas
> I can't make the swap function work either.
> So I have to use a temporary variable :)
> Please take a look at my changes and let me know if you have any issues with the changes

Looks great, love the clean up especially on the reordering - moving away from allocating an array of 3 to a single one is a good move! Looking good to go I think?

2023-06-29 03:59 UTC, SoftFever approved these changes

2023-06-29 04:01 UTC, SoftFever commented
Cool. Good to merge.

Currently this optimisation apply to Arachne, do you want to optimise the classic wall generator(in process_classic() function)?

2023-06-29 04:02 UTC, merged