Update Snapmaker Profiles
SoftFever/OrcaSlicer pull request #1421
Opened 2023-06-24 16:37 UTC by macdylan

I own Snapmaker A350&J1, and here I have corrected and validated all the parameters for Snapmaker printers.

2023-06-24 16:53 UTC, hliebscher commented
Currently @fr3ak2402 is helping consolidate the printer profile names.
Can you refer to this: https://github.com/SoftFever/OrcaSlicer/pull/1100#issuecomment-1556946352 to match the new name schema?

2023-06-24 18:51 UTC, macdylan commented
<img width="375" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/331506/34e7b00e-104b-4139-8232-ddf79061ba50">

@hliebscher Is this acceptable?

I noticed that filament no longer distinguishes between Nozzles in the new rules, and personally i think this unreasonable. Or did I miss something? 

in the Assets filenames, some are in lowercase while others are in uppercase, and this is a bit confusing to me.
<img width="286" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/331506/47917419-edc4-440e-bdf8-cb3637237f98">

2023-06-24 19:21 UTC, fr3ak2402 commented
@macdylan 

I have also considered different filaments for the nozzles, in the 2.x version of the profiles... At the time when I had set the new naming system, there were only 0.4 nozzles.

Since some things have changed for me, I have for example started to create all profiles with more nozzle sizes. I am also in the process of creating all the filaments for each nozzle. I will use the scheme from Bambulab with the `@base, @0.2 nozzle, @0.4 nozzle` and so on.

----------------------------------
Can you rename the J1 filaments, e.g. Snapmaker J1 PLA @0.4 nozzle etc.?

----------------------------------
In version 2.x the assets are also stored in a location in the profile, but you can leave that for now....

If you want, you can also create a PR in the OrcaSlicer Profile Library, you can find it under my repositories...

2023-06-25 16:19 UTC, SoftFever commented
@macdylan
Thank you for the PR. This is fantastic.

There will be some issue when we rename a file or profile, it will cause issues for existing user profiles that were created based on the older names. Those profiles will no longer be able to be loaded if we change the names.

To address this, I will write up a guide about profiles for OrcaSlicer. Once that is complete, I will review the PR and provide my comments.

2023-07-26 15:06 UTC, SoftFever requested changes

2023-07-26 15:06 UTC, SoftFever commented on resources/profiles/Snapmaker/filament/Snapmaker Generic ABS.json
Deleting or renaming an existing preset will make all existing user presets based on it unusable.
Can we avoid renaming or deletion?

2023-08-02 12:50 UTC, closed without merging