Spanish translation update and error in english string "outer_only"
SoftFever/OrcaSlicer pull request #1794
Opened 2023-08-14 18:41 UTC by tadeu2

outer_only should be Outer brim only, can you correct in pot file too?

2023-08-18 11:14 UTC, SoftFever requested changes
Hi @tadeu2 
Thanks for the PR.
Overall it looks good.
If you can revert the .gitignore changes, we can merge it.

2023-08-18 11:14 UTC, SoftFever commented on localization/i18n/en/OrcaSlicer_en.po
> +msgstr "Outer brim only"
Nice catch.

2023-08-18 11:14 UTC, SoftFever commented on localization/i18n/es/OrcaSlicer_es.po
👍

2023-08-19 00:07 UTC, tadeu2 commented
Feel free to edit all my PR

El vie, 18 ago 2023, 13:14, SoftFever ***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
>
> Hi @tadeu2 <https://github.com/tadeu2>
> Thanks for the PR.
> Overall it looks good.
> If you can revert the .gitignore changes, we can merge it.
> ------------------------------
>
> In .gitignore
> <https://github.com/SoftFever/OrcaSlicer/pull/1794#discussion_r1298316821>
> :
>
> > @@ -25,4 +25,5 @@ build_*/
>  SVG
>  src/OrcaSlicer-doc/
>  .idea/
> -/.cache/
>
> @tadeu2 <https://github.com/tadeu2> The .mo files are needed.
> Can we revert the change?
> ------------------------------
>
> In localization/i18n/en/OrcaSlicer_en.po
> <https://github.com/SoftFever/OrcaSlicer/pull/1794#discussion_r1298331275>
> :
>
> > @@ -6983,7 +6983,7 @@ msgid "Mouse ear"
>  msgstr ""
>
>  msgid "outer_only"
> -msgstr ""
> +msgstr "Outer brim only"
>
> Nice catch.
> ------------------------------
>
> On localization/i18n/es/OrcaSlicer_es.po
> <https://github.com/SoftFever/OrcaSlicer/pull/1794#discussion_r1298331393>
> :
>
> 👍
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SoftFever/OrcaSlicer/pull/1794#pullrequestreview-1584350746>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AENP5KTGXTWEXNZNTRVBLB3XV5FCRANCNFSM6AAAAAA3QCNB7Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-19 01:40 UTC, SoftFever approved these changes

2023-08-19 01:41 UTC, SoftFever commented
👍 
Merged.

2023-08-19 01:42 UTC, merged