20231018 Update Flashforge printer profiles: Adventurer 5M and Adventurer 5M Pro
SoftFever/OrcaSlicer pull request #2450
Opened 2023-10-18 12:09 UTC by FlashforgeOfficial

Hi, 
Lately I tested the profiles on a local clone of Orca. The printer profiles can now be selected and loaded with success. 
Let me know if the PR still doesn't match the main software.  Thanks!

2023-10-19 13:34 UTC, SoftFever requested changes

2023-10-19 13:34 UTC, SoftFever commented on resources/profiles/Flashforge/.vs/Flashforge/FileContentIndex/3f995606-d940-48a3-b978-2919ce9135e5.vsidx
Can you remove .vs folder?

2023-10-19 13:43 UTC, SoftFever commented
@FlashforgeOfficial 
Thanks. The profiles can be loaded properly.

I noticed some potential issues in the profiles though:
1. The origin is set in center of the bed, this may or may not be a bug. But it's unusual to have origin in the center for non-delta printer. Please double check.
2. The machine is using absolute E distance instead of recommended relative E distance. We need to reset E distance in layer change gcode for absolute  E distance. Slice a cube you will see the errors.
3. It's recommended to use transparent background color for the bed texture

2023-10-19 14:00 UTC, RafBois commented
Hello, can I get a profile for the Guider3Plus? 

The FlashForge slicer (FlashPrint) is just impossible to use (I'm on a Mac) with a room that takes up the volume of this printer.
The settings options for the FlashPrint slicer are extremely limited.
The machine lacks a lot of options to be considered a professional machine.

2023-10-20 02:03 UTC, FlashforgeOfficial commented on resources/profiles/Flashforge/.vs/Flashforge/FileContentIndex/3f995606-d940-48a3-b978-2919ce9135e5.vsidx
Sure, this folder will be removed in the next PR.

2023-10-20 02:29 UTC, FlashforgeOfficial commented
> @FlashforgeOfficial Thanks, the profiles loaded correctly. I did notice some potential issues however, can you confirm?
> 
> 1. The origin is in the bed's center. It's rare for non-delta printers to have this setting. Can you double-check?
> 2. The machine uses absolute E distance, not the recommended relative E distance. With absolute E distance, we must reset the E distance in the layer change gcode. Slice a cube, and you'll see the errors.
> 3. It's recommended to use a transparent background for the bed texture.

Yes, for tip1 the Flashforge printers use the bed's center for origin by default so we will keep the setting unless something goes wrong. For tips 2 and 3 we will double check and make the improvements. Thank you!

2023-10-20 03:08 UTC, FlashforgeOfficial commented
> Hello, can I get a profile for the Guider3Plus?
> 
> The FlashForge slicer (FlashPrint) is just impossible to use (I'm on a Mac) with a room that takes up the volume of this printer. The settings options for the FlashPrint slicer are extremely limited. The machine lacks a lot of options to be considered a professional machine.

Hi 

> Hello, can I get a profile for the Guider3Plus?
> 
> The FlashForge slicer (FlashPrint) is just impossible to use (I'm on a Mac) with a room that takes up the volume of this printer. The settings options for the FlashPrint slicer are extremely limited. The machine lacks a lot of options to be considered a professional machine.

Thank you @RafBois. Try using newest version of FlashPrint as there are some nice feature updates and might solve the issues. It is not clear if orca profile for G3 series would be setup for now, yet we will consider adding support for more machine profiles.

2023-10-23 15:49 UTC, RafBois commented
You can't even read change logs. It's already half-developed. Frankly above FlashForge. I don't understand why they want to close everything with their software? What's in it for them?
![Capture d’écran 2023-10-23 à 17 42 07](https://github.com/SoftFever/OrcaSlicer/assets/50773923/ea7fb1ad-07d1-42f9-8351-1de511bbeb99)

Best regards

2023-10-24 07:49 UTC, mariuske commented on resources/profiles/Flashforge/machine/Flashforge Adventurer 5M Pro 0.4 Nozzle.json
@FlashforgeOfficial - It looks like the nozzle specific parameters are copied from the 0.6 nozzle file and not adjusted for a 0.4 Nozzle. Examples (might be others as well):
	"nozzle_diameter": [ "0.6" ],
	"printer_variant": "0.6",
	"z_hop": [ "0.6" ],

2023-10-24 08:34 UTC, closed without merging

2023-10-25 03:25 UTC, FlashforgeOfficial commented on resources/profiles/Flashforge/machine/Flashforge Adventurer 5M Pro 0.4 Nozzle.json
Thank you for the advice!  I am fixing them in the lastest PR.