Fuzzy skin fixes + on/off for first layer
SoftFever/OrcaSlicer pull request #2903
Opened 2023-11-27 00:27 UTC by andrewboktor

Fixing fuzzy skin so it doesn't exit the desired geometry at line ends
Adding option to enable/disable fuzzy skin on first layer

Fixes #2891

2023-11-27 13:28 UTC, Noisyfox requested changes

2023-11-27 16:14 UTC, andrewboktor commented on src/libslic3r/PerimeterGenerator.cpp
> +        for (; p0pa_dist < p0p1_size;
This seems to deal with the situation where the line is too small to place a "pa" point on, in which case Cura seems to be placing a "pa" point in the middle of said line.
I feel like here, dist_left_over should deal with that (by accumulating length of short lines until we're eligible to add a "pa" point).
I will take a more in depth look later today. If you have geometry that makes this misbehave, please share, I think that would be really helpful.

2023-11-28 03:25 UTC, Noisyfox commented on src/libslic3r/PerimeterGenerator.cpp
> +        for (; p0pa_dist < p0p1_size;
I don't have much experience with this feature TBH so I couldn't give any feedback on this. I think it shouldn't matter too much for most of the models anyway.
I'll approve the PR and if you think it's OK to merge without those lines then just let me know.

2023-11-28 03:25 UTC, Noisyfox approved these changes

2023-11-28 07:36 UTC, andrewboktor commented on src/libslic3r/PerimeterGenerator.cpp
> +        for (; p0pa_dist < p0p1_size;
@Noisyfox Those lines are not here anyway in the current state. So I think we should be fine merging as is. 
I've been slicing 4-5 different models and printing them perfectly with this PR.
If we have a resident expert on fuzzy skin, we should have them take a look, if not then we should be fine to merge.

2023-11-28 07:40 UTC, Noisyfox commented on src/libslic3r/PerimeterGenerator.cpp
> +        for (; p0pa_dist < p0p1_size;
> Those lines are not here anyway in the current state. So I think we should be fine merging as is.

Fare enough, and we can always add those later if needed easily. Will merge as is, thanks!

2023-11-28 07:40 UTC, merged