New profile for Creality Ender 3 V3 KE
SoftFever/OrcaSlicer pull request #3216
Opened 2023-12-21 06:27 UTC by bistory

This PR adds a new profile for Creality Ender 3 V3.
Previous PR (#3192) was automatically closed, so I open this one...

It hasn't been tested (yet), however, I have the machine so I will fine-tune the profiles if needed.
Basically, it's a Ender 3 V3 SE with a better hotend and running on Klipper...

2023-12-21 08:36 UTC, SoftFever requested changes

2023-12-21 08:36 UTC, SoftFever commented on resources/profiles/Creality/filament/Creality Generic PLA High Speed @Ender-3V3-all.json
> -    "compatible_printers": [
Due to some code issue, we need to specify compatible_printers in all instantiatiable profiles for now.
So, for now let's maintain/update this property

2023-12-21 08:36 UTC, SoftFever commented on resources/profiles/Creality/filament/Creality Generic PLA Matte @Ender-3V3-all.json
> -	"compatible_printers": [
same

2023-12-21 08:36 UTC, SoftFever commented on resources/profiles/Creality/filament/Creality Generic PLA Silk @Ender-3V3-all.json
> -		"Creality Ender-3 V3 SE 0.4 nozzle"
same

2023-12-21 08:39 UTC, bistory commented
Thanks, it's done ;-)

2023-12-21 08:49 UTC, bistory reviewed
Reverted code simplification

2023-12-21 08:51 UTC, SoftFever commented
Thank you for the quick response.
Looks good now.

2023-12-21 08:51 UTC, SoftFever approved these changes

2023-12-21 08:51 UTC, merged

2023-12-21 08:59 UTC, SoftFever commented
@bistory 
I found one more thing we missed for V3 SE/KE,
The default materials are not updated which will cause first time user not see proper materials.
We need to update them as well
```
"default_materials": "Creality Generic PLA;Creality Generic PETG;Creality Generic ABS"
```
in file:
resources/profiles/Creality/machine/Creality Ender-3 V3 SE.json
resources/profiles/Creality/machine/Creality Ender-3 V3 KE.json

2023-12-21 09:03 UTC, bistory commented
> @bistory I found one more thing we missed for V3 SE/KE, The default materials are not updated which will cause first time user not see proper materials. We need to update them as well
> 
> ```
> "default_materials": "Creality Generic PLA;Creality Generic PETG;Creality Generic ABS"
> ```
> 
> in file: resources/profiles/Creality/machine/Creality Ender-3 V3 SE.json resources/profiles/Creality/machine/Creality Ender-3 V3 KE.json

Thanks for the feedback I fixed it, do you need a new PR ?

2023-12-21 09:05 UTC, SoftFever commented
> > @bistory I found one more thing we missed for V3 SE/KE, The default materials are not updated which will cause first time user not see proper materials. We need to update them as well
> > ```
> > "default_materials": "Creality Generic PLA;Creality Generic PETG;Creality Generic ABS"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in file: resources/profiles/Creality/machine/Creality Ender-3 V3 SE.json resources/profiles/Creality/machine/Creality Ender-3 V3 KE.json
> 
> Thanks for the feedback I fixed it, do you need a new PR ?

👍 
Yes, please.

2023-12-29 16:55 UTC, Alexgrau88 commented
Hello guys, im new to 3d print world, curios about one issue I'm facing with a Ender3V3KE, installed OrcaSlicer_Windows_Installer_1.8.1.exe , but I'm not saying the printer profile, am I missing something? I see that pull 3216 is merged, is it not committed to V 1.8.1 ?

2023-12-29 17:23 UTC, bistory commented
> Hello guys, im new to 3d print world, curios about one issue I'm facing with a Ender3V3KE, installed OrcaSlicer_Windows_Installer_1.8.1.exe , but I'm not saying the printer profile, am I missing something? I see that pull 3216 is merged, is it not committed to V 1.8.1 ?

V1.8.1 is 3 weeks old, this PR is one week old ;-)
This PR is already available in v1.9.0-alpha and improvements are in development on my side, I plan to make a new PR as soon as possible before v1.9.0 final release :-)

2023-12-29 17:33 UTC, Alexgrau88 commented
> > Hello guys, im new to 3d print world, curios about one issue I'm facing with a Ender3V3KE, installed OrcaSlicer_Windows_Installer_1.8.1.exe , but I'm not saying the printer profile, am I missing something? I see that pull 3216 is merged, is it not committed to V 1.8.1 ?
> 
> V1.8.1 is 3 weeks old, this PR is one week old ;-) This PR is already available in v1.9.0-alpha and improvements are in development on my side, I plan to make a new PR as soon as possible before v1.9.0 final release :-)

Yes indeed, i tried the 1.9.0 and its there. Thanks for the reply

2024-04-12 04:24 UTC, esn814 reviewed
Nice work ppl