Redesign of all icons / UI improvements
SoftFever/OrcaSlicer pull request #4368
Opened 2024-03-07 22:43 UTC by yw4z

I will try to add screenshots of latest design with less clutter as much as possible. only i couldn't work bamboo lab monitor screen because i don't know how to access that screen without bamboo machine

I will continue to send commits so they are not final images

will edit this post over time

### OVERALL GOALS
• Make UI to easier to use with better presented icons
• Improving UI consistency
• Make them unique to Orca Slicer
• Making all icons to pixel perfect

![Screenshot-20240308003830](https://github.com/SoftFever/OrcaSlicer/assets/28517890/f5682018-d188-4be5-b266-cff6322bb96c)

### TITLE BAR
old vs new
![Screenshot-20240308005955](https://github.com/SoftFever/OrcaSlicer/assets/28517890/90e25771-5a76-4f96-9f51-b2d435dae273)

### TOOLBAR
old vs new
![Screenshot-20240308010418](https://github.com/SoftFever/OrcaSlicer/assets/28517890/ba96403d-3899-4678-acc3-d0f269fba50d)

i recommend this order for for icons for best grouping
![Screenshot-20240308004504](https://github.com/SoftFever/OrcaSlicer/assets/28517890/cb4f6c55-eaaf-4ffc-b71d-40dbde4e4871)

### SIDEBAR
![Screenshot-20240308010647](https://github.com/SoftFever/OrcaSlicer/assets/28517890/b22d6e09-2409-43c4-bd9f-f0a664cab857)

![Screenshot-20240308010904](https://github.com/SoftFever/OrcaSlicer/assets/28517890/6fbf4df3-d2b5-4f9d-a9bc-9b44efa25cb5)

![Screenshot-20240308011727](https://github.com/SoftFever/OrcaSlicer/assets/28517890/ee9b485e-6412-43c6-b7c2-fd8977d540bc)

### PLACEHOLDER

![Screenshot-20240308005624](https://github.com/SoftFever/OrcaSlicer/assets/28517890/21153b73-e865-4908-8f1c-58cec2519117)

![Screenshot-20240308005741](https://github.com/SoftFever/OrcaSlicer/assets/28517890/8a3f8043-4e7b-44cf-bcfd-798446ef28e7)

### TOOLBAR POPUP WINDOW ICONS
Brush shape / type
![Uploading Screenshot-20240308011855.png…]()

Emboss > text alignment / style
![Screenshot-20240308011932](https://github.com/SoftFever/OrcaSlicer/assets/28517890/5ca36638-8dc2-4a0d-ab80-838de52b9860)

![Screenshot-20240308012152](https://github.com/SoftFever/OrcaSlicer/assets/28517890/7a3ebecc-558e-4b47-9541-e7e61268fd45)

### MODIFIER / OBJECT LIST ICONS / CONTEXT MENU

![Screenshot-20240308012947](https://github.com/SoftFever/OrcaSlicer/assets/28517890/d3a6d788-8594-4e29-9ab4-caf6e3adfeca)

### MENUBAR

![Screenshot-20240308013117](https://github.com/SoftFever/OrcaSlicer/assets/28517890/6643471d-face-4ab3-8278-fefbdeb02d88)

### VARIOUS

**LAYER VIEW MODE BUTTON**
![Screenshot-20240308005142](https://github.com/SoftFever/OrcaSlicer/assets/28517890/4bf80863-98c4-4192-92b1-0f7bba56af63)
• Size of icon increased around %150. here is compararison of size change. new vs old
![Screenshot-20240305105429](https://github.com/SoftFever/OrcaSlicer/assets/28517890/b0a5b73c-8177-45a9-a556-72a38acd3879)
• Removed size change on hovered images. used color change instead

### RELATED / FOUND BUGS
I have navigated all UI to find related icons and here is my findings
I will add pictures for all of them

**Bugs**
• Process > Objects > Object list > not changes color of modifier icons. if icon is black its not possible to see on dark mode
• Toolbar icons blurry [4328]( https://github.com/SoftFever/OrcaSlicer/issues/4328)
• Toolbar > Emboss > Advanced > Alignment buttons blurry ( this might be related with toolbar position )
• Toolbar > Emboss > Style > Buttons not rendered on correct resolution (16x16). this causes blurry icons  ( this might be related with toolbar position )
• Context menu > Split > not changed color of icons. if icon is black its not possible to see on dark mode. they are white on toolbar. its ok to remove icons instead of fixing it
• Printer Network Connection > Test icon rendered with wrong color if button disabled
• Toolbar > Measure >  a button appears for "copy to clipboard" after measuring but it uses "notification_arrow_right.svg". it can use menu_paste.svg with 16x16 resolution for fix

**UI inconsistencies**
• Process > Objects > Edit in parameter table > enable support > revert icon uses "lock_normal.svg" instead of "revert_btn.svg"
• Process > Objects > Object list > revert icon uses "lock_normal.svg" instead of "revert_btn.svg"
• Process > Objects > Search close button not uses "im_text_search_close.svg"
• Toolbar > Cut > Revert button always visible. It will only show up if value changed on other parts of UI
• Toolbar > Cut > Add connectors > plug / Snap > revert / reset buttons always visible
• Toolbar > Cut > Add connectors > radio buttons not using default style with radio_off.svg / radio_on.svg
• Toolbar > Emboss > Radio buttons for join cut modifier not using default style with radio_off.svg / radio_on.svg

**Other (Not related with icons, mostly UI inconsistencies)**
• Process > Objects > Edit in parameter table > value / input boxes not visible until click
• Clicking other toolbar button not closes variable layer height popup. also clicking outside not closing popup
• Toolbar > Emboss > Height and depth not uses step value box. they use + / - buttons but other parts of UI uses step boxes
• Filament settings > multi material > ramming settings > button not styled with dark theme
• Filament settings > multi material > ramming settings > popup window not works with dark theme
• Multiple plate slice > All bed stats text color is green (bamboo studio color)
• Context menu > Simplify Model > Color of Apply button is not Turquoise while hovering. is green (bamboo studio color)
• Compare presets row highlighting is making too much contrast. and it makes hard to read rows
• Window resize icon right bottom is not compatible with dark theme
• Title bar buttons not uses Turquoise background while hover
• Toolbar > Emboss > Advanced expansion button not uses Turquoise background while hover
• Toolbar > Emboss > Advanced > Sliders not uses Turquoise background for thumb
• Toolbar > Support Painting / Seam painting > Brush type selection radio button border not uses Turquoise background for active button
• Multiple sliced plates > selected plate thumbnail border not using Turquoise color

### THESE SHOULD BE CHANGE IN CODE
• Added height_range_modifier.svg for context menu "height range modifier" item
• Sidebar > Process > Global > Added new icons for titles (param_overhang, param_bridge, param_wall_surface, param_overhang_speed, param_jerk)
• There are many alignment related problems on UI. i can create mockups for proper aligments of icons if someone want to fix this

### REQUESTS / SUGGESTIONS
• Noticed this order would be better for toolbar icons
![Screenshot-20240308004504](https://github.com/SoftFever/OrcaSlicer/assets/28517890/c23f5106-712e-4985-a4a6-6741dd48a396)
• Sidebar > Process > Replace advance text with new atomic (advanced) icon
![Screenshot-20240308004615](https://github.com/SoftFever/OrcaSlicer/assets/28517890/02e392a5-1698-4a16-8ca4-a09c529a0588)
• Toolbar > Scale > Not uses world coordinates term for XYZ axes. Also removing world coordinates text from Move and Rotate will make their popups smaller
• i guess there are many unused images in images folder. there is many calibration related png images but UI not contains them. they take about 4-5MB space. Also there are many for store or account related images but orca not using these features

### WHAT IM NOT HAPPY ABOUT OR WILL REWORK
• Toolbar > Auto orient
• Toolbar > Lay on Face (this too are too much similar)
• Toolbar Popup Windows > Keyboard Cheat sheet button
• Toolbar > Color painting. Using same shapes on paint icons looks really nice but i'm planning to rework this one
• Slice > Preview > Legend can use eye icon to toggle visibility of elements (travel moves, infill etc.)
• Didn't touched orca slicer logo usages yet. want to add radius on background for dialog boxes and want to edit about page image

### HELP NEEDED
couldn't find or test these
• add.svg
• automatic_material_renewal.svg
• bind_machine.svg
• color_picker_border
• completed.svg
• copy_menu.svg
• flush_volumes.svg
• go_last_plate.svg
• go_next_plate.svg
• im_gcode_cust [...]

2024-03-08 05:48 UTC, Eldenroot commented
Thank you!!!

2024-03-08 12:54 UTC, discip commented
@yw4z
## First of all thank you for putting all the effort into improving this side of OrcaSlicer. 😃👍🚀

If I'am allowed to add my 2 cents here:

Some observations I made:

1. Did you intentionally design the icons so that they are not centered on themselves?
2. Is there a reason to revert the PNG optimization of #4294?
3. Some of the current icon designs are more intuitive and would only need to be adapted without a complete redesign (e.g. the resize icon). If you don't mind I would look through them and make some kind of a list of what should be kept.

2024-03-08 20:41 UTC, yw4z commented
@discip ofc everyone can share their thoughts and ideas about this

1. if you ask notification close buttons. i tried to reduce job on coding side. if you ask it for 16x16px images, i used 15x15px to get perfect center of icon. otherwise small icons will be pixelated with anti aliasing
2. i guess that's my mistake, i have started project a time ago. i will replace file on my source if its correct way to solve. let me know if there is an better way to solve this. because i'm still trying to learn how to use commit system
3. I tried to increase similarity between transform icons. All formed around on a simple box object.  So user can identify / find transform section on toolbar easier. Move icon has horizontal / vertical arrows, rotate has a simple circular arrow, scale has diagonal arrows that shows a bigger box also arrows matches corners between them
![Screenshot-20240308232509](https://github.com/SoftFever/OrcaSlicer/assets/28517890/56c58fd2-1822-44e0-9bea-dcc43332571c)

I tried to add a logic on every icon design. Ofc there is many ways to skin the cat. I tried to add the logic on icons on previous post but main post turned too much cluttered. so i didn't add this one. Dont hesitate to share your ideas or comments. this commit still in work in progress and this designs are not 100% final

And one more point. prusa / bamboo lab / ... and there is many more sharing similar designs. Using different designs will be better to making orca unique

2024-03-08 22:32 UTC, discip commented
1. I don't know what exactly you mean 😊, but almost every SVG looks like this:

   ![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/9de228a0-e39a-41bf-8c51-cb621d063959)

2. You could sync your fork:

   ![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/dba5531a-0a6d-4e7a-962a-ec9c9dc1f508)

3. I thought about something like this:

   ![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/fb3a53c8-569e-49fc-89a3-6212959461d3)

2024-03-08 23:05 UTC, yw4z commented
i guess this will explain
![Screenshot-20240309012846](https://github.com/SoftFever/OrcaSlicer/assets/28517890/b8a2e211-2e33-40d4-a5d8-b1d1b0ef9f64)
but i will choose using full of 16x16px if i use icons with 2px line width

here is a preview of your suggestion for transform icons, i have to draw dashed lines manually later to improve quality 
![Screenshot-20240309014557](https://github.com/SoftFever/OrcaSlicer/assets/28517890/56997ab0-9908-4a73-b9a8-25927c1ccd91)
Comparison with other transform icons
![Screenshot-20240309015546](https://github.com/SoftFever/OrcaSlicer/assets/28517890/aa387f5d-4f0c-4592-a90f-e17c5572ebad)

2024-03-08 23:37 UTC, discip commented
> i guess this will explain
> ![Screenshot-20240309012846](https://private-user-images.githubusercontent.com/28517890/311389755-8f6b57cf-2b99-414f-81a0-51e7578436d5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NDEyNDYsIm5iZiI6MTcwOTk0MDk0NiwicGF0aCI6Ii8yODUxNzg5MC8zMTEzODk3NTUtOGY2YjU3Y2YtMmI5OS00MTRmLTgxYTAtNTFlNzU3ODQzNmQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDIzMzU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMTY3OTJiN2VhOWU1YWVhMzcxMzMyMjE3ODEzY2Q2NTVlZDBjMzZiOTI5YTk2ZDgxZGMzNGVlN2IyYTdhZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fLP_iIV1yg5rs6hnArvlZhCTovGqoPjfeSMhnDzcNXg)
> but i will choose using full of 16x16px if i use icons with 2px line width

I think this is going to be fixed by @Noisyfox.

2024-03-09 00:06 UTC, yw4z commented
no that bug related with wrong placement of toolbar and not related with this. this one is much more how pixels work with anti aliasing

2024-03-10 11:02 UTC, igiannakas commented
Oh this is nice!! 👌🏻

2024-03-11 06:35 UTC, discip commented
> here is a preview of your suggestion for transform icons, i have to draw dashed lines manually later to improve quality
> ![Screenshot-20240309014557](https://private-user-images.githubusercontent.com/28517890/311387560-56997ab0-9908-4a73-b9a8-25927c1ccd91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzg3MjEsIm5iZiI6MTcxMDEzODQyMSwicGF0aCI6Ii8yODUxNzg5MC8zMTEzODc1NjAtNTY5OTdhYjAtOTkwOC00YTczLWI5YTgtMjU5MjdjMWNjZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA2MjcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZGM1NGUwNWRmYjc4Y2I2NzdkMzU4ZDk5NzI1NWEzY2JjNTdlM2NkNjY5MTY5NWY0MTA2ZThmZWQ4MTM1NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u1rV155pFtG6feLGOXH92_Ffa1dVjVW_28p2dJECDF8)
> Comparison with other transform icons
> ![Screenshot-20240309015546](https://private-user-images.githubusercontent.com/28517890/311388599-aa387f5d-4f0c-4592-a90f-e17c5572ebad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzg3MjEsIm5iZiI6MTcxMDEzODQyMSwicGF0aCI6Ii8yODUxNzg5MC8zMTEzODg1OTktYWEzODdmNWQtNGYwYy00NTkyLWE5MGYtZTE3YzU1NzJlYmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA2MjcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2M2UxYWY1Y2YwZWJhMzgzYWUxZjkyODBlNGVhN2ZmYTFlMmQ3M2ZhZmQwOTVjYTQyZmFlMTA2ZTNjODBkYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cWY8CWXOWzYNBMVCjy-o4reWc2XYxUnMIhHDwe11foc)

## Yes, that looks great! 👍🏻

As you've probably noticed, I've also added some comments to some of your designs.

2024-03-11 08:28 UTC, Noisyfox commented
> > i guess this will explain
> > ![Screenshot-20240309012846](https://private-user-images.githubusercontent.com/28517890/311389755-8f6b57cf-2b99-414f-81a0-51e7578436d5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NDEyNDYsIm5iZiI6MTcwOTk0MDk0NiwicGF0aCI6Ii8yODUxNzg5MC8zMTEzODk3NTUtOGY2YjU3Y2YtMmI5OS00MTRmLTgxYTAtNTFlNzU3ODQzNmQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDIzMzU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMTY3OTJiN2VhOWU1YWVhMzcxMzMyMjE3ODEzY2Q2NTVlZDBjMzZiOTI5YTk2ZDgxZGMzNGVlN2IyYTdhZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fLP_iIV1yg5rs6hnArvlZhCTovGqoPjfeSMhnDzcNXg)
> > but i will choose using full of 16x16px if i use icons with 2px line width
> 
> I think this is going to be fixed by @Noisyfox.

No gaurantee on this one TBH. There are lots of places that do the location & size calculation and care must be taken when updating those places. The fact that openGL does not render things based on pixels but percents of the render target/texture size etc. makes this quite hard to do pixel perfect rendering. Also things like anti-aliasing can make image blury too, and we cannot simply turn that off, otherwise we will have issues #2739

2024-03-11 09:02 UTC, discip commented
@Noisyfox
### No intention of applying pressure. I'm just optimistic about all the successes you've achieved so far. 😃🚀🎉

2024-03-11 10:56 UTC, yw4z commented
@Noisyfox can you check toolbar position as pixels? maybe adding a second step to shift it to an int number will fix it. I saw this problem only on toolbar and toolbar popups. probably popup positions related to toolbar and fixing toolbar will fix them too.

@discip where is your additional comments?

2024-03-11 14:33 UTC, discip commented
@yw4z
Please see the posts after the following one:
https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986516917

2024-03-11 15:00 UTC, yw4z commented
i read your comment [comment](https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986516917)
and answered in here. did you read [comment](https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986544994)

also you can use comment feature on files section to comment on a specific design. but its still an early stage. i'm changing designs constantly

2024-03-11 16:28 UTC, discip commented
1. > did you read [comment](https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986544994)

   Yes, I did here: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1987720659

2. > also you can use comment feature on files section to comment on a specific design.

   That's exactly what I did, but since there is unfortunately no way to link to those comments I linked the only one I could to, which happens to be this one: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986516917
   And I also wrote that it is not the one I linked to but all the other ones following the linked one.
   I hope this is clear now.
   
   Basically all the posts between these 2:

   https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986516917
   `                            .                               `
   `                            .                               `
   `                            .                               `
   https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986544994

2024-03-11 16:29 UTC, discip commented
@yw4z
1. > did you read [comment](https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986544994)

   Yes, I did and also answered here: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1987720659

2. > also you can use comment feature on files section to comment on a specific design.

   That's exactly what I did, but since there is unfortunately no way to link to those comments I linked the only one I could to, which happens to be this one: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986516917
   And I also wrote that it is not the one I linked to but all the other ones following the linked one.
   I hope this is clear now.
   
   Basically all the posts between these 2:

   https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986516917
   `                            .                               `
   `                            .                               `
   `                            .                               `
   https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986544994

2024-03-11 17:42 UTC, nevack commented on resources/images/add.svg
Looks like this is wrong.
`add` became a "minus"

2024-03-11 17:43 UTC, nevack commented on resources/images/check_half copy.svg
Looks like accidental file addition

2024-03-11 17:44 UTC, nevack commented on resources/images/custom-gcode_object-info copy.svg
Another accidental `copy` file?

2024-03-11 17:50 UTC, yw4z commented on resources/images/add.svg
thanks for correction. fixed on next commit. this file currently not visible in UI. will be add after code side changes

2024-03-11 18:03 UTC, nevack commented
@yw4z I do not have anything to say design-wise, but there are some more "accidental" copy files.
Please, recheck for any stale files and remove them.

Also, browser tab with this PR diff hangs for me forever, so I advise anybody who would like to check if all icons are changed correctly to use external tools, like [fork](https://fork.dev/), to have local rich diff.

2024-03-11 18:16 UTC, yw4z commented
@nevack yes thanks for pointing them. removed now
currently using github desktop
and exporting svg from illustrator using this settings
![Screenshot-20240311210041](https://github.com/SoftFever/OrcaSlicer/assets/28517890/ee17aa4b-9d3b-4dde-9498-6609f1198ec4)
im not sure maybe its related with browser trying to open 300+ svg files
same thing happening on this [commit](https://github.com/SoftFever/OrcaSlicer/commit/eae2703610b31b4d410540f60e95f407f1587bf8) with a lot of PNG. i guess its related with github

2024-03-11 19:54 UTC, discip requested changes

2024-03-11 19:59 UTC, discip commented on resources/images/toolbar_text.svg
The missing **`a`** makes it look like some kind of generic profile.
Please either return the **`a`** or replace the **`T`** with an **`A`**.

2024-03-11 20:02 UTC, discip commented on resources/images/topbar_redo.svg
Please make sure the arrow doesn't go all the way around.
I know the original design is a little harder to implement, but it actually looks nicer. 😊

2024-03-11 20:03 UTC, discip commented on resources/images/topbar_undo.svg
Same as **_`topbar_redo.svg`_**.

2024-03-11 20:05 UTC, discip commented
@yw4z
Now you should be able to see the comments I was referring to.

2024-03-11 20:05 UTC, yw4z commented on resources/images/align_vertical_bottom.svg
thanks! there are many icons. its easy to miss. will be corrected on next commit

2024-03-11 20:08 UTC, yw4z commented on resources/images/confirm.svg
it appears in Toolbar > Emboss > Font selection > Type in search box > Its much more logical to use arrow. mostly used this way in many UI

2024-03-11 20:08 UTC, yw4z commented on resources/images/confirm_dark.svg
it appears in Toolbar > Emboss > Font selection > Type in search box > Its much more logical to use arrow. mostly used this way in many UI

2024-03-11 20:10 UTC, yw4z commented on resources/images/cross.svg
I couldnt find this images in UI. let me know if you find. maybe its just a lefover. i added these to leftover list until someone finds it

2024-03-11 20:15 UTC, yw4z commented on resources/images/topbar_redo.svg
didnt get this one. is there a problem. its very readable on UI. i'm trying to use line based design as much as possible. so original design will not fit for these arrows. also please send single message for related ones

2024-03-11 20:15 UTC, yw4z commented on resources/images/topbar_undo.svg
replied in [resources/images/topbar_redo.svg](https://github.com/SoftFever/OrcaSlicer/pull/4368/files/c773c793e5707c517e827bffa3aca5084f26786e#diff-e8260fbd306a2a863bbe805b91512f6c1cc88fb46dff27e8575aa78cfc9dc866)

2024-03-11 20:16 UTC, yw4z commented on resources/images/toolbar_text.svg
I changed this design already for next commit. its nicer now. check again on next commit

2024-03-11 20:20 UTC, yw4z commented on resources/images/menu_support_blocker.svg
not planning to use multiple colors. it will break simplicity. also updated this for next commit
Cross is much more bigger, and this design preserves vertical lines that indicating its a support
![Screenshot-20240311231119](https://github.com/SoftFever/OrcaSlicer/assets/28517890/24ab119f-2adb-4a25-a0c7-3e66b25e30bf)

2024-03-11 20:22 UTC, yw4z commented on resources/images/menu_fuzzy_skin.svg
This one is not visible in UI either. Let me know if you find. also i didnt make a second round fixes in this because didnt saw in UI

2024-03-11 20:23 UTC, discip commented on resources/images/topbar_redo.svg
> didnt get this one.

The arrow you used goes almost 360° around wich would imply no change, since it ends in the same place where it left, in contrast to an arrow making only a 180° revolve.

> also please send single message for related ones

Sorry, I thought this would help.
Will do next time.

2024-03-11 20:24 UTC, yw4z commented on resources/images/toolbar_measure.svg
what did you expect ? i choose this one because it fits better on toolbar. and you are looking all icon designs on max resolution. they will look much more different in screen resolution

2024-03-11 20:25 UTC, yw4z commented on resources/images/toolbar_modifier_sphere.svg
Did you see this UI? its not visible on UI

2024-03-11 20:27 UTC, discip commented on resources/images/toolbar_measure.svg
Sorry, you are absolutely right!

2024-03-11 20:28 UTC, yw4z commented on resources/images/custom-gcode_measure.svg
you are looking at giant resolution again. normally its just 16x16px
This one should be add in code
filament/printer settings > advanced > gcode > click edit button > placeholders

2024-03-11 20:31 UTC, yw4z commented on resources/images/lock_normal.svg
this fixed in next commit

2024-03-11 20:38 UTC, yw4z commented on resources/images/revert_btn.svg
You ending every day in same bed but not waking up in same day. can you explain :) jokes beside, lock_normal.svg will be harder to read if i reduce length of arrow. decreasing 1px will not make a huge difference

2024-03-11 20:40 UTC, yw4z commented on resources/images/param_overhang_speed.svg
Actually changed snail with turtle on next commit. i try to add some ocean related elements to UI

2024-03-11 20:42 UTC, yw4z commented on resources/images/notification_expand.svg
This icon used on daily tips and expands to bottom. works as expected. like i said before you need to see in UI before comment.

2024-03-11 20:42 UTC, yw4z commented on resources/images/notification_collapse.svg
This icon used on daily tips and expands to bottom. works as expected. like i said before you need to see in UI before comment.

2024-03-11 20:44 UTC, yw4z commented on resources/images/im_all_plates_stats_transparent.svg
Its not transparent in original too. This is visible when processing multiple sliced plates. so works it works normal

2024-03-11 20:48 UTC, yw4z commented on resources/images/height_range.svg
This will change in next commit. fourth one.

![Screenshot-20240311233905](https://github.com/SoftFever/OrcaSlicer/assets/28517890/57ff1b17-36b7-4772-bb2a-40200c6d7d92)

 icon visible in Toolbar > Paint related buttons

2024-03-11 21:30 UTC, Eldenroot commented
What about the section - found BUGs (UI inconsistencies, related issues) - it will be fixed too by you?

2024-03-11 21:40 UTC, yw4z commented
@Eldenroot no i dont have enough knowledge for them. some help on them will be nice. but "THESE SHOULD BE CHANGE IN CODE (NEED HELP ON THIS)" this section more important because it will show new icons in UI. then fixing bugs later

2024-03-12 13:26 UTC, discip commented
@yw4z
So you are not going to use these icons?

![311387560-56997ab0-9908-4a73-b9a8-25927c1ccd91](https://github.com/SoftFever/OrcaSlicer/assets/53649486/19a8ae5a-75cb-4968-92f8-5cac6f590fc5)

2024-03-12 13:47 UTC, Eldenroot commented
@igiannakas would.you take care?

2024-03-12 13:52 UTC, yw4z commented
@discip i'm not sure about them. they are not filling icon frame enough that causes they look not good as changes ones. will try to rework later

2024-03-12 15:19 UTC, discip commented
## Great, thanks! 👍🏻

2024-03-12 20:08 UTC, discip commented on resources/images/toolbar_text.svg
I'm actually using the **text feature** a lot and unfortunately I can't get used to the design you chose, because this feature does not only **add** text but also **indents** or **modifies** _(e.g. fuzzy skin)_ the part of the object intersected by the text.

Please get me right: I absolutely appreciate what you do here, since I have done something similar to the UI of a **`JG Aurora`** some time ago.

But this design is not as intuitive as it could be, as it looks like some generic profile (T-beam).
Could you please revert that back to **2D** and maybe an **`A`** instead of a _**`T`**_? 😊

2024-03-13 15:10 UTC, SoftFever commented
Hi @yw4z 

Thanks for taking the initiative. 
Just a quick heads-up: It'll take me some time to start reviewing the designs.

2024-03-13 21:09 UTC, yw4z commented
@SoftFever no need to hurry, i'm still making changes on designs. ofc feel free to send any comments

2024-03-14 09:43 UTC, HahBikes commented
> @yw4z So you are not going to use these icons?
> 
> ![311387560-56997ab0-9908-4a73-b9a8-25927c1ccd91](https://private-user-images.githubusercontent.com/53649486/312093041-19a8ae5a-75cb-4968-92f8-5cac6f590fc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDk2NDUsIm5iZiI6MTcxMDQwOTM0NSwicGF0aCI6Ii81MzY0OTQ4Ni8zMTIwOTMwNDEtMTlhOGFlNWEtNzVjYi00OTY4LTkyZjgtNWNhYzZmNTkwZmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA5NDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YzRmNWVhYWQ2NTExMDBkYjY5ZjJhMzQyZTU0YzlkZTY4ODQyMGRmODk5NGM0OTlkZmFmYzE3MWZjYWVjZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bn_FjWnFAiLy_JQrwn22niUILT8g_CPXoOXnuc945nU)

These icons do seem more intuitive to me compared to the other ones. It would be great if somehow we can incorporate these.

2024-03-15 03:31 UTC, dekay commented
Have you been able to test these changes under Linux? There are a number of UI bugs like [invisible text](https://github.com/SoftFever/OrcaSlicer/issues/3667) and [issues with dark mode](https://github.com/SoftFever/OrcaSlicer/issues/3882).

2024-03-15 10:58 UTC, yw4z commented
@dekay Nope i only tested on windows maybe they are not related with icon changes. But i will add them to bug list on first post because its related with UI

2024-03-15 12:09 UTC, discip commented
@yw4z
You are right these issues are not related to the changes you made and were present prior to your **icon upgrade**. 😃

2024-03-15 15:38 UTC, yw4z commented
@discip FYI changed undo / redo icons. used slightly shorter arrow on them but kept revert icons same because its putting their value to original value (putting back to same place where they came). this usage makes more sense. i guess you are a more happy person today :)

2024-03-19 01:32 UTC, Noisyfox commented
Regarding the reordering of the toolbar icons, this will need some major changes to the toolbar rendering logic, because currently although it looks like there is one single uniformed toolbar on the top, it's actually rendered by 3 separated modules in the app (the main toolbar, the gizmo toolbar and the assemble toolbar), hens the 2 separaters and 3 segments of the toolbar.

2024-03-19 02:03 UTC, yw4z commented
@Noisyfox Can we move items between 3 modules? Reordering items on toolbar will improve usability of toolbar. I guess we can solve with less work. this order has less moves
![Screenshot-20240319045053](https://github.com/SoftFever/OrcaSlicer/assets/28517890/24adbfd1-8ef8-4915-95d3-317998c446a1)

2024-03-19 02:26 UTC, Noisyfox commented
> @Noisyfox Can we move items between 3 modules? Reordering items on toolbar will improve usability of toolbar. I guess we can solve with less work. this order has less moves ![Screenshot-20240319045053](https://private-user-images.githubusercontent.com/28517890/313888384-24adbfd1-8ef8-4915-95d3-317998c446a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTU0NTgsIm5iZiI6MTcxMDgxNTE1OCwicGF0aCI6Ii8yODUxNzg5MC8zMTM4ODgzODQtMjRhZGJmZDEtOGVmOC00OTE1LTk1ZDMtMzE3OTk4YzQ0NmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAyMjU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NDU5ZDc3NjhhNzk4ZDBhYjg2M2ZlYTFhNWIyYmM0YjNkNTQ3ZmMwM2I2OWI0MDIxMWQ3NzdiMTZjNTQ4YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.84fPmEEVCGrOIAlLxxd23AMvef0fjhm3pgu3Xnum90s)

Unfortunately that's not possible at the moment.

2024-03-19 02:43 UTC, yw4z commented
Can you just replace emboss with color painting? i guess this one is most logical for now. used same design for painting functions but emboss is like "hey im here"

![Screenshot-20240319053153](https://github.com/SoftFever/OrcaSlicer/assets/28517890/90446f50-a48d-477e-99cf-69e53961cdf5)

2024-03-19 02:48 UTC, Noisyfox commented
> Can you just replace emboss with color painting? i guess this one is most logical for now. used same design for painting functions but emboss is like "hey im here"
> 
> ![Screenshot-20240319053153](https://private-user-images.githubusercontent.com/28517890/313896081-90446f50-a48d-477e-99cf-69e53961cdf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTY3NzUsIm5iZiI6MTcxMDgxNjQ3NSwicGF0aCI6Ii8yODUxNzg5MC8zMTM4OTYwODEtOTA0NDZmNTAtYTQ4ZC00NzdlLTk5Y2YtNjllNTM5NjFjZGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAyNDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYWVhMjIxMTBmZjljNGJiNzAwOTQwMDFjODYzMzU3NzEwOGZkZWU4NWY3YzhhZDczMGJjMThlMDc2N2NmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BH6NnW83fSgUzVDd0wVYaECVpkLMuK41mao-BJHIytw)

Do you mean switch the position of emboss & color paint icons? Yeah that can be done for sure.

2024-03-19 02:51 UTC, yw4z commented
Yes exactly. Thanks

2024-03-19 02:55 UTC, Noisyfox commented
You could even do this yourself, there are simply 2 list you need to adjust:
https://github.com/SoftFever/OrcaSlicer/blob/b736a0bc385217fb3440f4b9bf802de96dd51e90/src/slic3r/GUI/Gizmos/GLGizmosManager.hpp#L77-L98
and 
https://github.com/SoftFever/OrcaSlicer/blob/b736a0bc385217fb3440f4b9bf802de96dd51e90/src/slic3r/GUI/Gizmos/GLGizmosManager.cpp#L193-L209

2024-03-19 03:01 UTC, yw4z commented
lol i hate C :) mostly work on javascript and no experience on C. don't want to break something

is there a way to show simplify button on toolbar? i was searching reduce_triangles.svg on UI. And looks like a button for SVG but didnt saw that too

2024-03-19 03:07 UTC, Noisyfox commented
> lol i hate C :) mostly work on javascript and no experience on C. don't want to break something
> 
> is there a way to show simplify button on toolbar? i was searching reduce_triangles.svg on UI. And looks like a button for SVG but didnt saw that too

No we don't show simply on toolbar, it's accessable only from context menu, similar to the svg gizmo.

2024-03-19 03:09 UTC, yw4z commented
i thought there is a condition for that. i will send a commit to change icon order tomorrow

2024-03-19 17:50 UTC, yw4z commented
@SoftFever @Noisyfox
Designs mostly done. planning to send only minor changes after this point except changes related with your comments
i recommend you to read first post with expandable sections. added many required information to them
Please don't hesitate on any type of comments.
bamboo lab monitor icons included in file changes. only i didn't touch resources/web folder
I can restore bamboo lab icons if you want to not include them. %70 of them not pixel perfect.
I have no bbl printer so couldn't test icons properly on monitor UI
Added required changes and UI related bugs / improvements to first post. They can be solve on another commit

2024-03-21 01:18 UTC, SoftFever commented
Thank you!I will only have time to do a code review after 2.0 release.Sent from my iPhoneOn 20 Mar 2024, at 1:50 AM, yw4z ***@***.***> wrote:﻿
@SoftFever @Noisyfox
Designs mostly done. planning to send only minor changes after this point except changes related with your comments
i recommend you to read first post with expandable sections. added many required information to them
Please don't hesitate on any type of comments.
bamboo lab monitor icons included in file changes. only i didn't touch resources/web folder
I can restore bamboo lab icons if you want to not include them. %70 of them not pixel perfect.
I have no bbl printer so couldn't test icons properly on monitor UI
Added required changes and UI related bugs / improvements to first post. They can be solve on another commit

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-03-25 10:45 UTC, discip commented on resources/images/undo.svg
Was this accidentally reverted or did you change your mind about this post: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1999929107 ?

2024-03-25 10:45 UTC, discip commented on resources/images/toolbar_rotate.svg
What about the design of the transformation tools?
As mentioned here: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1997038997, I'm not the only one who finds the previous design more appealing.
If you are still aiming for similarity (https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986388081), all transformation tools should use dashed lines, which are already used in the following design:
![311387560-56997ab0-9908-4a73-b9a8-25927c1ccd91](https://github.com/SoftFever/OrcaSlicer/assets/53649486/19a8ae5a-75cb-4968-92f8-5cac6f590fc5)

You mentioned that you would revise this later: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1991704267

2024-03-30 20:53 UTC, discip requested changes

2024-03-30 20:53 UTC, discip commented on resources/images/toolbar_flatten.svg
@yw4z
What is that crosshair supposed to represent?
Either this should be present on all the other transformation tools as well, or - much easier - it should be removed from this one here, otherwise this breaks consistency.

2024-03-30 20:53 UTC, discip commented on resources/images/undo.svg
@yw4z
Was this accidentally reverted or did you change your mind about this post: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1999929107 ?

2024-03-30 20:53 UTC, discip commented on resources/images/toolbar_rotate.svg
@yw4z
What about the design of the transformation tools?
As mentioned here: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1997038997, I'm not the only one who finds the previous design more appealing.
If you are still aiming for similarity (https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1986388081), all transformation tools should use dashed lines, which are already used in the following design:
![311387560-56997ab0-9908-4a73-b9a8-25927c1ccd91](https://github.com/SoftFever/OrcaSlicer/assets/53649486/19a8ae5a-75cb-4968-92f8-5cac6f590fc5)

You mentioned that you would revise this later: https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-1991704267

2024-04-04 21:31 UTC, discip commented
@yw4z
See, same as last time.
Still no answers. 🤷🏻 😟

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/c7f129ee-a945-4356-bd35-180db0cac835)

2024-04-04 22:01 UTC, discip commented
Sorry, I did not mean to make you uncomfortable in any way.

Thank you for answering.

2024-04-10 13:38 UTC, SoftFever commented
@yw4z 
Thanks for the fantastic work!
I have a few feedback:
1. the splash screen is a bit too "pop up"/"eye catching" IMO.
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/378dc729-7c34-415f-9d84-eec9f6e42f01)
I'd prefer to keep the previous minimalist style:
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/ae1dc8fc-104a-41e8-87a5-c3b7b6152950)

2. I feel the orientation related new icons are not very intuitive
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/1a94d1f5-c78e-4d57-bfe9-3f991257f07f)
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/0abefbf5-a9cf-4348-91a2-d320224fdfec)
The old icons are self explainable for comparison. It conveys a implicit message: orient the part so flat surface are laid on the bed. It also makes sense to add "auto" text for the "Auto orientation" icon.
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/c3b48b98-1fa0-440a-9c52-86a63b027586)
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/3f18bf47-4e6c-474f-a78e-82805bf5917e)

3. Would it be better to have a `+` on the Add plate icon?
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/b16676ef-ea89-4e79-a47c-6530cd4a2633)

4. The paint support/seam icons are not very intuitive IMO
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/fc053983-4994-4b3e-bd20-c044c120226b)
The old icons did a better job here IMHO.

Others icons looks fantastic!

2024-04-11 11:01 UTC, discip commented
>    I'd prefer to keep the previous minimalist style:
>    ![image](https://private-user-images.githubusercontent.com/103989404/321253820-ae1dc8fc-104a-41e8-87a5-c3b7b6152950.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzMyNDQsIm5iZiI6MTcxMjgzMjk0NCwicGF0aCI6Ii8xMDM5ODk0MDQvMzIxMjUzODIwLWFlMWRjOGZjLTEwNGEtNDFlOC04N2E1LWMzYjdiNjE1Mjk1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxMDU1NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWNjY2NmNDE0ODQ5NjczZWEwM2IwOTg0OTg2N2U2MWMyMTQ5ZjY4ZGRmYjczOTFkMTE4ZmQ3OGMzMTRiNThmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r4ww-Uh8Flm1sX2pfxLupJOisjLS1FEI40VVCPAkWfU)

Maybe a white border would make the logo stand out better from the background?

2024-04-11 13:26 UTC, StuSerious commented
@yw4z Incredible work you've done here! 
Professional level UX and UI, thoughful considerations and overall a massive improvement to the look and feel of Orca!
Thank you ❤️

2024-04-11 21:13 UTC, yw4z commented
@StuSerious thanks for your comment. still there are many things to do. its just beginning :) i hope we can merge without hustle

@SoftFever i will rework that icons. i guess you want to keep simple as much as possible and not liking fancy stuff.  like @discip 's suggestion, problem is icon is not visible on dark background

here is an alternative design. also tried to simplify typeface of logo
![Screenshot-20240412000120](https://github.com/SoftFever/OrcaSlicer/assets/28517890/959003d2-e278-4a26-9e5e-e159011c334f)

2024-04-12 00:44 UTC, SoftFever commented
> here is an alternative design. also tried to simplify typeface of logo ![Screenshot-20240412000120](https://private-user-images.githubusercontent.com/28517890/321786906-959003d2-e278-4a26-9e5e-e159011c334f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODE4MzgsIm5iZiI6MTcxMjg4MTUzOCwicGF0aCI6Ii8yODUxNzg5MC8zMjE3ODY5MDYtOTU5MDAzZDItZTI3OC00YTI2LTllNWUtZTE1OTAxMWMzMzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAwMjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZTEzMzFhNjE3N2YzMTE4NDk0ZmRhZjgyODYwYzE1MjU5MWMwOGZmNmNmOTcwMjkwNjQzN2Q1Mzk3Zjk1NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IrQkw047sKNSEgA7b1zjL1XVjSiSybHhTmZOFaI1XlE)

This looks great!

> @SoftFever i will rework that icons. i guess you want to keep simple as much as possible and not liking fancy stuff. like @discip 's suggestion, problem is icon is not visible on dark background

Hehehe, yeah, I prefer to keep icons simple and intuitive. They should be easy to memories and difference between different tools.
This is especially true for the toolbar icons as we don't display name for this tools

2024-04-12 04:39 UTC, just-trey commented
I applaud your efforts here, as this is a big undertaking. I want to add a few comments that would improve this. 

I agree with others that some of the icons can be kept the same and are more intuitive the way they are. I think alternatives should be looked at for split objects and parts. I don't like the originals much either, but teh way you have them, they may be less intuitive. 

The other thing I noticed is that I am seeing some color contrast issues that will hurt accessibility for visually challenged users. The grey-on-grey here does not pass accessibility guidelines. I suggest increasing the contrast. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/10281380/0cae9922-2268-4528-b4bd-bd4999dcd804)

The active modified state of this icon also has contrast issues that should be addressed. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/10281380/7b09ea5e-6974-4d98-9904-5a49864129cd)

I am also willing to help some here, but some hard-core coding stuff needs to be up my alley.

2024-04-22 21:13 UTC, yw4z commented
@SoftFever 
There is still too much things on my list but i guess its on a good point to start testing / reviewing and wondering your comments on code changes.
I'm not waiting for full code review but if you take a look quickly. you will get idea. I'm sure some changes could be integrate better
About code changes looks like there is enough people maintain UI related things. What's your thought about this?

I'm planning to split this to smaller commits after it completely done. perhaps this will make it easier to review

2024-04-22 21:20 UTC, yw4z commented
@just-trey 
Can you use this about a week? wondering your comments after long term usage. Maybe you should check your contrast setting on your monitor if you struggled to see edit icons. you will start to loose details on your monitor with contrast setting above 70. btw i dimmed them slightly with purpose. They repeating too much on UI on some sections like Emboss gizmo / filaments. this will tire eye

2024-05-01 06:49 UTC, SoftFever commented
@yw4z 
As discussed on Discord, I've solved the conflicts and reverted code changes in this PR so that we can focus on icons here.
I'm going to merge this pull request (PR), thank you for your fantastic work!
The new icons look really good 🥇

2024-05-01 07:05 UTC, SoftFever approved these changes

2024-05-01 07:05 UTC, merged

2024-05-01 07:31 UTC, yw4z commented
@SoftFever appreciated. always love to support good work. also some of icons requires code changes for activation then i will send a separate commit for them

2024-05-06 22:45 UTC, discip commented
@yw4z
As previously mentioned the arrows to expand / collapse the **`Daily Tips`** are mixed up.

Should be pointing up:

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/ba8eba1c-5e18-4b74-a661-4cfc8c9d4429)

Should be pointing down:

![image](https://github.com/SoftFever/OrcaSlicer/assets/53649486/bcc88a4f-6247-428f-ab40-1e06591fb8fe)

2024-05-06 22:50 UTC, yw4z commented
@discip send problems to this commit https://github.com/SoftFever/OrcaSlicer/pull/5221

2024-06-01 23:10 UTC, xros commented
To be honest, new icons are welcome but I prefer some old icons. Because some old icons are very intuitive while some new icons are over-designed. 

**Icons should be straight-forward, explaining itself with great readablity**

2024-06-02 00:02 UTC, yw4z commented
@xros you can give some examples instead just throwing a comment. so we have an idea about which icons you pointing

2024-06-10 05:10 UTC, kvnper commented
> To be honest, new icons are welcome but I prefer some old icons. Because some old icons are very intuitive while some new icons are over-designed.
> 
> **Icons should be straight-forward, explaining itself with great readablity**

 

I agree with this.

Some examples from the top bar:

* The measure icon being calipers is less readable at a glance, it's too fine detailed.
* Same as above for material paint icon.
* Same for support and seam paint icons, with the addition that there is nowhere near enough differentiation to be readable without looking at the small details. Prusa Slicer has this same issue with some of their icons where the only differentiator is a small detail in the whole icon.

Almost every other icon on the top bar is either:
* unnecessarily changed for the sake of change
* Less readable than the old
* Too detailed/busy

I don't mean to discourage you but it's my opinion that this was not an improvement overall.

2024-06-10 18:34 UTC, yw4z commented
@kvnper i guess you misunderstood this point. Orca slicer is not copycat of bamboo studio or prusa. this project experiments on new printing techniques and deserves a unique design language on UI. Making UI "easy to migrate" should not be priority.  just give a time and you will get used to overtime if you use regularly

2024-06-12 01:08 UTC, kvnper commented
I don't think I misunderstood. And that's only one of the points I made,
which is the lesser of the points.

Sure I can get used to a worse design (for me) when I have no other choice,
but it's still a worse design for me.

On Tue, Jun 11, 2024, 4:34 AM yw4z ***@***.***> wrote:

> @kvnper <https://github.com/kvnper> i guess you misunderstood this point.
> Orca slicer is not copycat of bamboo studio or prusa. this project
> experiments on new printing techniques and deserves a unique design
> language on UI. Making UI "easy to migrate" should not be priority. just
> give a time and you will get used to overtime if you use regularly
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SoftFever/OrcaSlicer/pull/4368#issuecomment-2159039914>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALKJ3ALGXHLFRQ6VHYZOVF3ZGXWU3AVCNFSM6AAAAABEL25J4WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNJZGAZTSOJRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-12 01:22 UTC, yw4z commented
that looks like personal preference to me. sorry but there is no way to make everyone happy. also if you did indicate few points i could understand but you pointing whole changes as negative. i cant do much about it

2024-06-12 01:25 UTC, kvnper commented
> that looks like personal preference to me. sorry but there is no way to make everyone happy. also if you did indicate few points i could understand but you pointing whole changes as negative. i cant do much about it

Exactly, personal preference. I was voicing my opinion on this open discussion of an open source matter.

2024-06-12 01:30 UTC, kvnper commented
> that looks like personal preference to me. sorry but there is no way to make everyone happy. also if you did indicate few points i could understand but you pointing whole changes as negative. i cant do much about it

Let's focus going forward on the points you could understand, because pointing to this whole changes as negative was again, the lesser point of what I said after pointing out many other things that you could have commented on - which would shift it from negative to positive.

2024-06-12 08:42 UTC, StuSerious commented
I'll give my point of view since I'm subscribed to this issue, like others I imagine, to track further progress after release.

Without some proper explanations, possibly with screenshots and suggestions for change, it's hard to grasp what you want to convey and you're just turning it into a discussion. 
Take a look at how feedback was given further up in this thread for example.

Points like "too detailed", "less readable", "changed for sake of change" do very little in providing factual evidence for what you are suggesting.

2024-06-17 02:37 UTC, kvnper commented
> I'll give my point of view since I'm subscribed to this issue, like others I imagine, to track further progress after release.
> 
> Without some proper explanations, possibly with screenshots and suggestions for change, it's hard to grasp what you want to convey and you're just turning it into a discussion. Take a look at how feedback was given further up in this thread for example.
> 
> Points like "too detailed", "less readable", "changed for sake of change" do very little in providing factual evidence for what you are suggesting.

And what about the points above those, which are detailed and provide factual evidence?

2024-06-24 04:05 UTC, markaudacity commented
Really nice new look, @yw4z. Clean, consistent, and maintains a design language with the previous UI. Job well done.

2024-07-28 10:56 UTC, kvnper commented
Hi again,

I really like the improvements on these icons compared to before, there is enough differentiation in the iconography that it's a lot easier to tell at a glance which is which:
![image](https://github.com/user-attachments/assets/f36cc7ec-2d36-4234-95c8-d4c4907e8c4a)

I think with these right click context icons there could be more differentiation. I like to do the squint test to see if they look the same and it does not pass it. The - and + do not have enough visual weight to differentiate at a glance:
![image](https://github.com/user-attachments/assets/f7159640-23ed-4290-9dd3-abfc41f0e7f3)

All-in-all I'm liking the new icons since last time. Congratulations on a job well done.

2024-07-28 16:42 UTC, yw4z commented
@kvnper glad to see you back with positive comment. like i said new look requires some time. 
i have tried few different versions for modifier / object list related icons
![Screenshot-20240728193011](https://github.com/user-attachments/assets/b3fba81a-327c-4224-8a54-ae6bb9354a5a)

colorful one is most easy to use one but it made UI so "fancy" / colorful.

@SoftFever can you check colorful versions i didnt shared before
[colorful-icons.zip](https://github.com/user-attachments/files/16404537/colorful-icons.zip)

maybe i can it to [new ](https://github.com/SoftFever/OrcaSlicer/pull/6204) if approved by everyone

2024-07-28 17:28 UTC, kvnper commented
I only comment in the best interest of the quality of the softeare