Add spacing between icons of node on objects list if node has multiple icons
SoftFever/OrcaSlicer pull request #5321
Opened 2024-05-10 16:30 UTC by yw4z

New vs Old
![Screenshot-20240510060352](https://github.com/SoftFever/OrcaSlicer/assets/28517890/baff49f8-4009-422e-a112-ef0dda272912)

• used font size for spacing width. this also gives better result for scaling

how to get all 3 icons for same list item
• Pick a step file or use a model with open mesh
• Use cut and add connector then perform cut. ignore dialog for fix

Another scenario for multiple icons
• Add a cube
• Add a modifier
• Cut with pins
![Screenshot-20240510192034](https://github.com/SoftFever/OrcaSlicer/assets/28517890/00688b1f-a012-44fd-9eab-23e0c6aebec7)

I'm sure there are many other combos with / without cut

Also found this minor bug
• Scaling not works on that icons on original source if scaling changes while orca running

2024-05-18 14:44 UTC, SoftFever requested changes

2024-05-18 14:44 UTC, SoftFever commented on src/slic3r/GUI/ObjectDataViewModel.cpp
> +        if (node->has_warning_icon() && node->has_lock()) // ORCA: Add spacing between icons if there are multiple
The code would be simpler if we move these two lines in the next `if` block

if (node->has_lock()) {
    if(!bmps.empty())
        bmps.emplace_back(create_scaled_bitmap("dot", nullptr, int(wxGetApp().em_unit() / 10) * 4));
    bmps.emplace_back(m_lock_bmp);
}

2024-05-18 14:44 UTC, SoftFever commented on src/slic3r/GUI/ObjectDataViewModel.cpp
> +        if (is_volume_node && (node->has_lock() || node->has_warning_icon())) // ORCA: Add spacing between icons if there are multiple
Same here

2024-05-18 16:21 UTC, yw4z commented
@SoftFever updated code change. yes `!bmps.empty()` is simpler choose for condition

```
        if (node->has_warning_icon())
            bmps.emplace_back(node->warning_icon_name() == WarningIcon ? m_warning_bmp : m_warning_manifold_bmp);
        if (node->has_lock()) {
            if (!bmps.empty()) // ORCA: Add spacing between icons if there are multiple
                bmps.emplace_back(create_scaled_bitmap("dot", nullptr, int(wxGetApp().em_unit() / 10) * 4));
            bmps.emplace_back(m_lock_bmp);
        }
        if (is_volume_node) {
            if (!bmps.empty()) // ORCA: Add spacing between icons if there are multiple
                bmps.emplace_back(create_scaled_bitmap("dot", nullptr, int(wxGetApp().em_unit() / 10) * 4));
            bmps.emplace_back(
                node->is_text_volume() ? m_text_volume_bmps[vol_type] :
                node->is_svg_volume() ? m_svg_volume_bmps[vol_type] : 
                m_volume_bmps[vol_type]);
        }
```

2024-05-19 02:05 UTC, SoftFever approved these changes

2024-05-19 02:06 UTC, merged