Correct odd layer GUI description
SoftFever/OrcaSlicer pull request #5793
Opened 2024-06-21 11:41 UTC by vovodroid

Currently every second layer for "on odd layer" options is checked as `layer_id % 2 == 1`. Though from mathematics POV it's correct, but in GUI first layer is one and not zero, thus actually option is applied for even layers.

I guess this is SuperSlicer legacy, and this PR fix this confusing description in GUI.

![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/577842d2-4638-4f1e-bb4c-40af868a5ea1)

![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/f2eb4fb5-2929-409c-9b4b-729c50ff41c6)

2024-06-21 18:56 UTC, kisslorand commented
Isn't the first layer numbered "0"?

2024-06-21 20:28 UTC, vovodroid commented
In code yes, but in GUI first layer is "1".

2024-06-21 20:30 UTC, vovodroid commented
![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/9af0b4b9-2bb6-4fc1-b162-957687eb8796)

2024-06-24 07:36 UTC, vovodroid commented
Another option - call it "every other layer", like here

![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/23be3b02-20d1-437c-9668-8a08794beb68)

2024-07-29 10:56 UTC, SoftFever requested changes
Nice catch!
Can we change the code logic to make it align with the UI, but leave the text/description unchanged?
e.g.
change code from `layer_id % 2 == 1;` to `layer_id % 2 == 0;`

2024-07-29 11:00 UTC, vovodroid commented
Sure we can, but `layer_id % 2 == 0` includes first (zero) layer, thus demanding special handling. Also is change perimeters for all existing projects. So I guess change description is much better.

2024-07-29 12:18 UTC, SoftFever reviewed
The catch with changing user facing text is that it will invalidate all existing translations

2024-07-29 12:39 UTC, vovodroid commented
Translations could be updated, it's updated on GUI changes anyway.
Also expressions `layer_id % 2 == 0` will affect first layer, and  `layer_id > 0 && layer_id % 2 == 0` will skip two first layers, causing inconsistency in behavior.

2024-09-09 14:45 UTC, SoftFever commented
> Translations could be updated, it's updated on GUI changes anyway. Also expressions `layer_id % 2 == 0` will affect first layer, and `layer_id > 0 && layer_id % 2 == 0` will skip two first layers, causing inconsistency in behavior.

Good point :)

2024-09-09 14:45 UTC, SoftFever approved these changes
LGTM

2024-09-09 14:45 UTC, merged