Adaptive layers - respect layer height range modifiers.
SoftFever/OrcaSlicer pull request #5941
Opened 2024-06-30 06:15 UTC by vovodroid

This PR enforces Height Range Modifiers for Adaptive Layers. If object has such modifiers they layer height will be used and not be affected by Adaptive/Smooth/Editing:
 
![image](https://github.com/SoftFever/OrcaSlicer/assets/8691781/305e5e56-a63a-4999-ac9b-30a4ecf7031c)

2024-11-20 13:04 UTC, SoftFever requested changes
Sorry for the long delay. 
I've reviewed the changes and tested them; they work like a charm 👍 
I noticed you temporarily turned off optimization (see my other comment). 
Could you take a look at that? Otherwise, everything looks good to me.

2024-11-21 07:37 UTC, vovodroid commented on src/slic3r/GUI/GLCanvas3D.cpp
> +#pragma optimize("", off)
Removed

2024-11-21 07:40 UTC, vovodroid commented
I'm thinking about using zero value for not forcing layer height and using adaptive height.

2024-11-21 13:40 UTC, merged

2024-11-21 13:42 UTC, SoftFever commented
> I'm thinking about using zero value for not forcing layer height and using adaptive height.

I actually like the current behavior(with your changes), use zero value will make the logic less intuitive IMO.