Support threshold offset
SoftFever/OrcaSlicer pull request #6606
Opened 2024-08-30 09:56 UTC by vovodroid

This PR unlocks and configure overhang offset support threshold in addition to angle threshold. Actually angle threshold has no intrinsic meaning, because it's offset which affects overhangs quality. Angle that could be printed without support is function of layer width and height.

This option sets percent of not supported external perimeter width triggering support
![image](https://github.com/user-attachments/assets/750b52f1-72c1-4868-b521-adb93c1d2651)

Width 0.62, layer 0.32, offset threshold 50%
![image](https://github.com/user-attachments/assets/5ce06fdf-1728-4069-87f7-c12619911da3)

Width 0.62, layer 0.32, offset threshold 80%
![image](https://github.com/user-attachments/assets/b2156c35-a6eb-4829-b635-798318571718)

Width 0.62, layer 0.12, offset threshold 80%
![image](https://github.com/user-attachments/assets/c45284f4-90f9-4678-b082-36923e02957c)

2024-08-30 11:56 UTC, discip commented
> So we don't need to adjust offset threshold when layer height is changed.

# Nice! 👍

2024-08-30 11:57 UTC, discip commented
> So we don't need to adjust offset threshold when layer height is changed.

# Nice! 👍

Should get the QoL label.

2024-09-09 06:40 UTC, vovodroid commented
I thought about add absolute offset in addition to percent and reverse logic - i.e. use "overlap" instead of offset, though 15%/0.1mm means like this:

![image](https://github.com/user-attachments/assets/7b91924c-8cfd-4ece-a504-d271bbfe29d5)

Probably it's more intuitive than setting 0.5mm/85%.
Any thoughts?

2024-09-09 07:49 UTC, discip commented
> it's more intuitive than setting 0.5mm/85%.

That's is absolutely correct! 😃

2024-09-09 07:49 UTC, discip commented
> it's more intuitive than setting 0.5mm/85%.

That's absolutely correct! 😃

2024-09-09 10:23 UTC, vovodroid commented
Offset replaced with overlap (line width - offset).

2025-01-10 22:31 UTC, boromyr commented
+1 for this feature

2025-01-22 03:43 UTC, Noisyfox requested changes

2025-01-22 03:43 UTC, Noisyfox commented on src/libslic3r/PrintConfig.cpp
> +    def->tooltip = L("Support will be generated for overhangs whose overlap is below the threshold. The smaller this value is, the steeper the overhang that can be printed without support.");
Better to update the comment says to enbale this option the angle threshold should be set to 0 first.

2025-01-22 03:44 UTC, Noisyfox commented
LGTM, will merge once the tooltip is updated and conflicts are resolved

2025-01-23 09:36 UTC, vovodroid commented on src/libslic3r/PrintConfig.cpp
> +    def->tooltip = L("Support will be generated for overhangs whose overlap is below the threshold. The smaller this value is, the steeper the overhang that can be printed without support.");
Done.

2025-01-23 10:01 UTC, Noisyfox approved these changes
LGTM, thanks

2025-01-23 10:01 UTC, merged