feature:added option to save a profile as detached(no inheritance)
SoftFever/OrcaSlicer pull request #7071
Opened 2024-10-10 23:39 UTC by Azio-Pantheon

# Description
This gives users the ability to break the inheritance and have an independent user profile. It fixes #6323 and #4691. Works for machine/filament/process profiles.

Partially solves #1182, any profile name change in system profiles will cause user created profiles that are inheriting those system ones to fail to load. If you really hate system profile updates breaking your user profiles, you may now choose to save your user profiles as independent profiles. The obvious downside is, you now have to maintain your settings, and won't automatically get any updates from system profiles.(if you are already tinkering your own profiles, you probably don't want any changes to happen without your notice in the first place)
 

# Screenshots/Recordings/Graphs

**This option is only enabled under developer mode**:
![Screenshot 2024-10-10 163302](https://github.com/user-attachments/assets/54f00830-a037-4ecd-9acb-ae28528d7050)

![Screenshot 2024-10-10 163337](https://github.com/user-attachments/assets/a92940ef-76c4-4c26-8c03-d578545dae6a)

## Tests
tested locally on windows 11

2024-11-01 12:35 UTC, AlatusAles commented
Это самая ожидаемая, мною, функция!

2025-06-16 15:41 UTC, afmenez requested changes
I believe something went wrong with your commit, the diff is showing that SavePresetDialog.cpp and SavePresetDialog.hpp where fully replaced.

2025-06-27 11:46 UTC, cheatreal321 commented
Glad to see someone has taken the time to implement this feature. The existing profile management and dependencies are making it impossible to set up my 2T Prusa XL with different nozzle sizes in OrcaSlicer. Once this makes it to a nightly build I can finally see myself using OS and contributing to the project.

2025-07-23 23:40 UTC, turpinator commented
Great to see some active/recent work on this!  I just spent 30 mins pulling my hair out trying to figure out why newly saved profiles didnt appear in orca (and other odd profile behavior in the past which is explained by this).  I finally opened the .json files and saw the inherit and realized that was the issue all along.
Looking forward to seeing this get implemented!

2025-09-25 15:15 UTC, UnrealFakes commented
Did this ever get implemented? I don't see the option even after enabling dev mode :/

2025-12-23 14:48 UTC, csecsoliver commented
What's the state of this pull request?

2026-01-01 07:10 UTC, SoftFever commented
@Azio-Pantheon 
For the PR, any idea what happens when you save the profile without a parent profile? Does it store all the possible settings in this custom profile?

2026-01-05 20:09 UTC, Azio-Pantheon commented
> @Azio-Pantheon For the PR, any idea what happens when you save the profile without a parent profile? 

Not sure what you meant by "save the profile without a parent profile." But saving as detached will pull all the settings from the inherited chain and put it under one json file

2026-02-06 14:52 UTC, SoftFever commented
> > @Azio-Pantheon For the PR, any idea what happens when you save the profile without a parent profile? 
> 
> Not sure what you meant by "save the profile without a parent profile." But saving as detached will pull all the settings from the inherited chain and put it under one json file

cool, that was exactly what I asked :)

2026-02-06 15:01 UTC, SoftFever approved these changes
LGTM

Thank you!

2026-02-06 15:02 UTC, merged