Partition hot bed gcode processing
SoftFever/OrcaSlicer pull request #7184
Opened 2024-10-22 02:16 UTC by ELEGOOTechSupport

#6602

If the temperature of the other layer is different from the temperature of the first layer, it needs to be applied. To facilitate the setup of a hot bed with multi-zone control in a custom G-CODE.

If there is a better way to implement this request, please turn off this PR, thank you!

2024-11-12 16:01 UTC, ELEGOOTechSupport commented
Hi @SoftFever .  
Maybe take a look at this PR first, which is useful for printers with partitioned hot beds.

2024-12-24 13:32 UTC, SoftFever requested changes

2024-12-24 13:32 UTC, SoftFever commented on src/libslic3r/GCode.cpp
> +        int bed_temp_first = get_bed_temperature(first_printing_extruder_id, true, print.config().curr_bed_type);
Can you explain the changes in a bit more detail?
Seems the first_printing_extruder_id is not properly assigned anywhere; what are we expecting here?

2025-01-03 17:16 UTC, SoftFever commented
@ELEGOOTechSupport I'm closing this PR now.
Feel free to re-open it in case you plan to resume working on it.

2025-01-03 17:16 UTC, closed without merging