Add profiles for DeltaMaker 3D printers
SoftFever/OrcaSlicer pull request #7712
Opened 2024-12-09 15:08 UTC by DeltaMaker

# Description

This pull request adds support for DeltaMaker 3D printers, with profiles for the DeltaMaker 2, DeltaMaker 2T, and DeltaMaker 2XT.

These profiles are improved versions of the original DeltaMaker profiles that are distributed with Simplify3D.

# Screenshots/Recordings/Graphs

<img width="532" alt="printer-selection" src="https://github.com/user-attachments/assets/90154ebe-04cb-47c6-ba24-dd20be4b3907">

## Tests

These profiles have been tested on DeltaMakers running Klipper firmware, and on legacy printers running Marlin.

2025-01-12 09:54 UTC, christiancoleman commented
Thanks for the help @SoftFever. I've made a couple changes to two files, but I don't have permissions yet to make changes to this PR.
[fdm_machine_common.json](https://github.com/user-attachments/files/18388895/fdm_machine_common.json)
[fdm_process_common.json](https://github.com/user-attachments/files/18388896/fdm_process_common.json)
After these changes I get a `Validation completed successfully` message, but I was curious about the process at large. I see some of the profiles seem to be hard-coded in `CreatePresetsDialog.cpp` and I was curious if changes need to be made there too.

2025-01-17 12:59 UTC, christiancoleman approved these changes
Was able to get a successful validation using these changes. @SoftFever let me know if there is anything else I should look into.

2025-01-17 13:31 UTC, christiancoleman commented
Had to make a force change to remove the fact that the commit had come over as an old company git account (wrong author) that I still had in my shell. Cleaned up my shell and this commit. Let me know if you have any questions.

2025-01-22 06:32 UTC, Noisyfox requested changes

2025-01-22 06:32 UTC, Noisyfox commented on resources/profiles/DeltaMaker/machine/Deltamaker 2.json
Wrong file name I believe. Should be `DeltaMaker` not `Deltamaker`

2025-01-23 14:55 UTC, SoftFever commented
@DeltaMaker 
Please kindly review the errors again.

2025-01-23 20:30 UTC, DeltaMaker commented on resources/profiles/DeltaMaker/machine/Deltamaker 2.json
Yes, the file name was wrong. I just pushed the correction. Thanks

2025-01-23 23:11 UTC, Noisyfox approved these changes
LGTM, thanks

2025-01-23 23:11 UTC, merged