Update README.md
SoftFever/OrcaSlicer pull request #7806
Opened 2024-12-21 02:28 UTC by AtomicRobotMan0101

A trivial amendment to the initial graphics location to correct it from that of another fork, plus some trivial text edits to smooth reading.

Added a small text to encourage others to report spammy sites to the engines to have them eventually culled.

# Description

# Screenshots/Recordings/Graphs

## Tests

2024-12-26 08:39 UTC, TrentBartlem requested changes

2024-12-26 08:39 UTC, TrentBartlem commented on README.md
> +Please be aware that "**orcaslicer.net**" or "**orcaslicer.info**" are NOT an official website for OrcaSlicer and may be potentially malicious. These sites appear to use AI-generated content, lacking
"and seem"

2024-12-26 09:32 UTC, AtomicRobotMan0101 commented
done!

2024-12-26 09:50 UTC, AtomicRobotMan0101 commented
apologies.

2025-01-22 06:33 UTC, Noisyfox approved these changes

2025-01-22 06:33 UTC, merged