add QIDI X Plus 3 Printer Profile
SoftFever/OrcaSlicer pull request #846
Opened 2023-04-24 17:23 UTC by Musicdad12

These files contain the default QIDI profiles released for the QIDI X Plus 3 printer

2023-04-24 18:16 UTC, fr3ak2402 commented
Hi Musicdad12, 
I am currently also working on the implementation of the Qidi Tech printer profiles. Have you perhaps already tested the official profiles with the OrcaSlicer?

2023-04-24 19:39 UTC, Musicdad12 commented
> Hi Musicdad12, I am currently also working on the implementation of the Qidi Tech printer profiles. Have you perhaps already tested the official profiles with the OrcaSlicer?

I don't have this printer, so No, this is not tested. The values used in the profile are from QIDI released profiles. I am willing to update the profiles if you see anything is drasically wrong.

2023-04-24 20:03 UTC, fr3ak2402 commented
Okay. I had started to create the profiles for the Qidi Tech X-Max 3 & X-Smart 3 as well. Maybe we can both merge our profiles?

Can you perhaps create a profile for the Qidi X-Max from 2018? 
Qidi has also released an official profile for this printer.

2023-04-25 12:21 UTC, SoftFever commented
Cool, thanks @Musicdad12 
LGTM.

2023-04-25 12:22 UTC, SoftFever commented
@fr3ak2402 , if you want, I can merge this PR first then you can create new profiles based on the latest changes.
That should be easier for collaboration.

2023-04-25 12:32 UTC, fr3ak2402 commented
@SoftFever, yes we can do it that way.

I have used different names for the printer family, printers and filaments in my profiles, should I adapt these directly? So that my profiles match his or his profile of the X-Plus 3 matches the others of mine?

I only have one question about the setting_id and filament_id, how is the ID composed? In the Bambulab documentation, the id is always set to "xxx".

2023-04-25 13:21 UTC, SoftFever commented
@fr3ak2402 name in this PR looks fine to me. I suggest keep using these name styles unless you found something obviously wrong.

For the setting_id and filament_id, as long as we use the ones that are available in BBL profiles. This is to make sure they can be synced to the cloud.

2023-04-25 13:29 UTC, SoftFever requested changes

2023-04-25 13:29 UTC, SoftFever commented on resources/profiles/Qidi.json
Can you rename it to `QIDI.json` so that it matches QIDI folder? It may cause issues on Mac/Linux as their filenames are case-sensitive.

2023-04-25 13:32 UTC, fr3ak2402 commented
@SoftFever, well, I would have called the printer family Qidi Tech because that's the name of the manufacturer. But you can also leave it at Qidi.
I named the filaments "Qidi Tech Generic PLA", for example, because this is also the case with all other printers.

2023-04-25 13:37 UTC, fr3ak2402 commented
@SoftFever, you can have a look at my fork, I've already committed my own things there.

There you can see how I have done the naming. At the same time, I can already adjust the images to 512x512 pixels, etc.

Okay, so for the setting_id and filament_id, can I choose an id that has already been used in another profile or can I just choose any?

2023-04-25 14:00 UTC, SoftFever commented
@fr3ak2402 
Maybe "Qidi Generic PLA" is better and not that wordy?

If you don't mind, you can try PR your changes and other new profiles to @Musicdad12 's branch to consolidate effort?

2023-04-25 17:53 UTC, fr3ak2402 commented
@SoftFever, I have completed the adjustments and integrated @Musicdad12's work into mine.

I have replaced the Qidi X-Plus 3 printing plate with the correct plate from the manufacturer. The image of the printing plate is also 512x512 pixels.
I also corrected the json file of the printer where not all filaments were stored. 

I have adjusted my profiles for Qidi X-Max 3 & Qidi X-Smart 3 to work with the filaments from @Musicdad12.

I haven't finished the other printers from Qidi yet and will finish them in the next few days:
Qidi X-Max
Qidi X-CF Pro

Do you merge the PR from @Musicdad12 first or should I create a PR directly?

2023-04-26 14:09 UTC, Musicdad12 commented
> Okay. I had started to create the profiles for the Qidi Tech X-Max 3 & X-Smart 3 as well. Maybe we can both merge our profiles?
> 
> Can you perhaps create a profile for the Qidi X-Max from 2018? Qidi has also released an official profile for this printer.

Yes, I can. Do you have profiles on these?

2023-04-26 16:30 UTC, fr3ak2402 commented
@Musicdad12, you can find the profile of X-Max under the following link.
https://drive.google.com/drive/folders/1lH2puChl7MPDzgyj4kb9z61nuTQbHhUd

The profile of the X-Max is called PrusaSlicer_max.ini

Thank you for adopting the profile of Qidi X-Max.
While you're at it, maybe you can join the Qidi X-CF Pro? This profile is called PrusaSlicer_cf_pro.ini

2023-04-26 16:36 UTC, fr3ak2402 commented
@Musicdad12, I would also support you in creating the profiles. 

Yesterday I already created my own SVG files for the X-Smart 3, X-Plus 3 and X-Max 3.

I also saw yesterday that Qidi has revised the profiles for these printers. I already did that for the X-Plus 3, so you don't have to do it again.

If you want, you and I can continue to work together on the profiles of the Qidi printers in my fork of the OrcaSlicer. In my fork, I have already combined your and my profiles and adapted them so that other Qidi printers can be added later.

2023-04-27 14:04 UTC, SoftFever commented
Thanks @Musicdad12 
Since the work has been consolidated to https://github.com/SoftFever/OrcaSlicer/pull/868.
I'm closing this one.
I will credit both of you for the profile.

2023-04-27 14:04 UTC, closed without merging

2023-04-30 03:00 UTC, Musicdad12 commented
> @Musicdad12, you can find the profile of X-Max under the following link. https://drive.google.com/drive/folders/1lH2puChl7MPDzgyj4kb9z61nuTQbHhUd
> 
> The profile of the X-Max is called PrusaSlicer_max.ini
> 
> Thank you for adopting the profile of Qidi X-Max. While you're at it, maybe you can join the Qidi X-CF Pro? This profile is called PrusaSlicer_cf_pro.ini

I would like to work with you on the other profiles. Ia there a way of sending pm or email or discord or something?