Added profile for SecKit SK-Tank
SoftFever/OrcaSlicer pull request #858
Opened 2023-04-26 15:47 UTC by scottmudge

Added profile for SK-Tank (https://sites.google.com/view/seckit-wiki/sk-tank-350x350x400) CoreXY printer.

Some notes:

* Default max acceleration set to just above the recommended used in the klipper configs linked in the SecKit SK-Tank wiki.
* Added custom build-plate STL and logo. 
* I could not find any good "stock" image of the printer alone for the setup wizard image for the printer, so I used the SecKit logo instead.

2023-04-27 01:43 UTC, SoftFever requested changes

2023-04-27 01:43 UTC, SoftFever commented on resources/web/image/printer/SecKit SK-Tank_cover.png
Can you put a printer image instead?

2023-04-27 01:43 UTC, SoftFever commented on resources/profiles/SecKit/hotend.stl
we don't need this hotend.stl anymore

2023-04-27 06:28 UTC, scottmudge commented on resources/web/image/printer/SecKit SK-Tank_cover.png
Yeah I'll have to work some photoshop wizardry, but I'll see what I can do.

2023-04-27 06:28 UTC, scottmudge commented on resources/profiles/SecKit/hotend.stl
Good to know -- I didn't see it really used anywhere, but the other profiles had it, so followed convention. I'll delete it.

2023-04-27 20:14 UTC, scottmudge commented on resources/web/image/printer/SecKit SK-Tank_cover.png
Alright, took a lot of using the eraser tool and clone-stamp tool, but I created an image from the SecKit website: https://seckit3dp.design/img/sk-tank-main.webp

2023-04-27 20:15 UTC, scottmudge commented on resources/profiles/SecKit/hotend.stl
It's been removed

2023-04-27 20:15 UTC, scottmudge commented
Thanks for the review -- changes have been completed and PR updated.

2023-04-28 05:58 UTC, SoftFever approved these changes
LGTM.
Thank you

2023-04-28 05:59 UTC, merged